# Generated by Django 5.2.17 on 2026-09-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforms',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetails',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='status',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='stock_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_phone',
            field=models.PositiveIntegerField(),
        ),
    ]
