# Generated by Django 5.2.17 on 2026-09-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='sale_date',
            new_name='Sell_date',
        ),
    ]
