# Generated by Django 5.2.17 on 2026-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0002_rename_sale_date_sales_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Sell_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
