# Generated by Django 5.2.17 on 2026-10-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0003_alter_sales_sell_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
