# Generated by Django 5.2.17 on 2026-10-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0004_alter_platforms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Sell_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_products.sales')),
            ],
        ),
    ]
