# Generated by Django 5.2.17 on 2026-10-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0006_alter_productcategory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returns',
            old_name='date',
            new_name='return_date',
        ),
    ]
