# Generated by Django 5.2.17 on 2026-10-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_products', '0007_rename_date_returns_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_products.productdetails')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_products.suppliers')),
            ],
        ),
    ]
